[wokwi]
version = 1
gdbServerPort = 3333
elf = "target/xtensa-esp32s3-espidf/debug/std-simple-http-server"
firmware = "target/xtensa-esp32s3-espidf/debug/std-simple-http-server"

[[net.forward]]
from = "localhost:8180"
to = "target:80"